apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deploy
spec:
  selector:
    matchLabels:
      app: frontend-pod
  replicas: 1
  template:
    metadata:
      labels:
        app: frontend-pod
    spec:
      imagePullSecrets:
      - name: acr-secret
      containers:
        - name: frontend
          image: emreregistry.azurecr.io/frontend:latest
          imagePullPolicy: Always
          resources:
          ports:
            - containerPort: 4200
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  selector:
    app: frontend-pod
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 4200
